version: "3"
services:
  www:
    build: /home/cytech/trw/Python_Docker  # Utilisez le chemin du répertoire contenant le Dockerfile
    dockerfile: docker-compose.yaml
    ports:
      - "${PORT-8000}:5000"
    user: nobody
    environment:
      DEBUG: "1"  # Mettez la valeur entre guillemets
    command: python Calc_Age.py
    volumes:
      - ./www:/src
  redis:
    image: redis  # Changez l'image au besoin
#networks:
  #default:
    #external: 
      #name: localnet  # Indique que le réseau est externe

